### ISSUE TITLE
Unable to convert Level.sac using convert.cmd

### ISSUE THREAD

**Issue by Daemencer** [cheahjs/palworld-save-tools#136]
While trying to run convert.cmd on Level.sav, the log returns the following error:

`Checking if Python is installed as python3
INFO: Could not find files for the given pattern(s).
Checking if Python is installed as python
C:\Users\Tom\AppData\Local\Programs\Python\Python38-32\python.exe
Found Python at python
Python version:
Python 3.8.3
Traceback (most recent call last):
  File "convert.py", line 7, in <module>
    from palworld_save_tools.gvas import GvasFile
  File "D:\Apps\PalworldTool\palworld_save_tools\gvas.py", line 4, in <module>
    from palworld_save_tools.archive import FArchiveReader, FArchiveWriter
  File "D:\Apps\PalworldTool\palworld_save_tools\archive.py", line 86, in <module>
    None, bool, int, float, str, list["JSON"], dict[str, "JSON"], UUID, uuid.UUID
TypeError: 'type' object is not subscriptable`

I'm not sure if the initial warnings could be a problem?

Regardless, I get no file generated.
Thank you

**Comment by Daemencer** [comment]
I think a previous installation of python 3.8.3 was conflicting with the new 3.12 version.
I removed the previous installation and it seems to work.

I also had an issue with file permission but that's not directly related to your content.

Thank you for your program!
