### ISSUE TITLE
Exception: Warning: EOF not reached

### ISSUE THREAD

**Issue by Joey901201** [cheahjs/palworld-save-tools#138]
Common issues before reporting
NO
Have you modified the save files
NO
Have you tried the latest release
YES
Describe the bug
Can‘t convert level.sav into level.sav.json with the code below.

PS C:\Users\Downloads\palworld-save-tools-windows-v0.18.0>python convert.py "C:\Users\Downloads\palserver123\BA9C13FF41FDE4E008A18EA6C7EBE74A\Level.sav"
Converting C:\Users\Downloads\palserver123\BA9C13FF41FDE4E008A18EA6C7EBE74A\Level.sav to JSON, saving to C:\Users\Downloads\palserver123\BA9C13FF41FDE4E008A18EA6C7EBE74A\Level.sav.json
Decompressing sav file
Loading GVAS file
Traceback (most recent call last):
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\convert.py", line 160, in <module>
    main()
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\convert.py", line 71, in main
    convert_sav_to_json(
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\convert.py", line 114, in convert_sav_to_json
    gvas_file = GvasFile.read(
                ^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 279, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 292, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 403, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 430, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 279, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\archive.py", line 289, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\rawdata\group.py", line 17, in decode
    group["value"]["RawData"]["value"] = decode_bytes(
                                         ^^^^^^^^^^^^^
  File "C:\Users\Downloads\palworld-save-tools-windows-v0.18.0\palworld_save_tools\rawdata\group.py", line 77, in decode_bytes
    raise Exception("Warning: EOF not reached")
Exception: Warning: EOF not reached

Copy of .sav or .sav.json files
[Level.zip](https://github.com/cheahjs/palworld-save-tools/files/14200154/Level.zip)

**Comment by cheahjs** [comment]
The group data is corrupted by one-byte, do you need the save file to be recovered? Otherwise your best option is to start the server and make another save. The guild created by the player `howardlee0517` has a player count of zero instead of one, so the tool errors out.

**Comment by iFangg** [comment]
Hi, I've come across a similar issue. By making another save do you mean that I cannot transfer the desired local co-op save to a dedicated server (including player data)? Are there any other fixes to this issue? Is there a way to change the player count of the guild artificially?

**Comment by Henry-Hiles** [comment]
Hmm, I have the same error, but https://palworld.tf/ loads it just fine.

**Comment by misfit92** [comment]
getting same error above after feybreak update, reads the save before december 22nd just fine but post update throws the same error as above.
[PALSAVE error 1-7-25.txt](https://github.com/user-attachments/files/18334627/PALSAVE.error.1-7-25.txt)
