### ISSUE TITLE
Unable to convert files. "Exception: not a compressed Palworld save, found too many null bytes, this is likely corrupted"

### ISSUE THREAD

**Issue by 42nfl19** [cheahjs/palworld-save-tools#143]
**Have you modified the save files**
Unable to convert to Json

**Have you tried the latest release**
On latest version v0.18.0.

**Describe the bug**
Unable to convert file to json. Logs are as follows.
`C:\Users\42nfl19\AppData\Local\Microsoft\WindowsApps\python3.exe
Found Python at python3
Python version:
Python 3.12.2
Converting C:\Users\42nfl19\Documents\SteamCMD\steamapps\common\PalServer\Pal\Saved\SaveGames\0\1B4E1A1748F57D35EED45EB716E67ED1\Players\87BF90A4000000000000000000000000.sav to JSON, saving to C:\Users\42nfl19\Documents\SteamCMD\steamapps\common\PalServer\Pal\Saved\SaveGames\0\1B4E1A1748F57D35EED45EB716E67ED1\Players\87BF90A4000000000000000000000000.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "C:\Users\42nfl19\Desktop\PalBackupSaves\palworld-save-tools-windows-v0.18.0\convert.py", line 160, in <module>
    main()
  File "C:\Users\42nfl19\Desktop\PalBackupSaves\palworld-save-tools-windows-v0.18.0\convert.py", line 71, in main
    convert_sav_to_json(
  File "C:\Users\42nfl19\Desktop\PalBackupSaves\palworld-save-tools-windows-v0.18.0\convert.py", line 105, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\42nfl19\Desktop\PalBackupSaves\palworld-save-tools-windows-v0.18.0\palworld_save_tools\palsav.py", line 18, in decompress_sav_to_gvas
    raise Exception(
Exception: not a compressed Palworld save, found too many null bytes, this is likely corrupted`

**Copy of .sav or .sav.json files**
Files attached.
[CorruptedFiles.zip](https://github.com/cheahjs/palworld-save-tools/files/14227272/CorruptedFiles.zip)

**Comment by IvanT9567** [comment]
I have the same issue. Here's to hoping this will help increase the sample size!
[Corrupted Players.zip](https://github.com/cheahjs/palworld-save-tools/files/14346044/Corrupted.Players.zip)

**Comment by tys90** [comment]
Same issue
[Players.zip](https://github.com/cheahjs/palworld-save-tools/files/14628208/Players.zip)

**Comment by CSEliot** [comment]
Also issue, +1. No way to show partial successes during the conversion process??

**Comment by cheahjs** [comment]
> Also issue, +1. No way to show partial successes during the conversion process??

If the error you get is `not a compressed Palworld save, found too many null bytes, this is likely corrupted`, then the entire file is likely to be entirely zeroed out, so there's nothing to recover even partially.
