### ISSUE TITLE
Exception: incorrect compressed length: 1913

### ISSUE THREAD

**Issue by UyNewNas** [cheahjs/palworld-save-tools#161]
**Common issues before reporting**

**Have you modified the save files**
If you have, please ensure that the JSON files are valid.

**Have you tried the latest release**
Please download the `palworld-save-tools-windows.zip` file from [releases](https://github.com/cheahjs/palworld-save-tools/releases/latest) in case it's been fixed.

**Describe the bug**
```
Checking if Python is installed as python3
D:\Python310\python3.exe
C:\Users\timot\AppData\Local\Microsoft\WindowsApps\python3.exe
Found Python at python3
Python version:
Python 3.10.8
Converting H:\Pal\Saved\F4DEA5DF13C5415AB200CC02F68CA7D5\WorldOption.sav to JSON, saving to H:\Pal\Saved\F4DEA5DF13C5415AB200CC02F68CA7D5\WorldOption.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "H:\Pal\palworld-save-tools-windows-v0.20.0\convert.py", line 160, in <module>
    main()
  File "H:\Pal\palworld-save-tools-windows-v0.20.0\convert.py", line 71, in main
    convert_sav_to_json(
  File "H:\Pal\palworld-save-tools-windows-v0.20.0\convert.py", line 105, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
  File "H:\Pal\palworld-save-tools-windows-v0.20.0\palworld_save_tools\palsav.py", line 33, in decompress_sav_to_gvas
    raise Exception(f"incorrect compressed length: {compressed_len},{len(data)}")
Exception: incorrect compressed length: 1913,1926
```

**Copy of .sav or .sav.json files**
If possible, attach the .sav or .sav.json file. Add to a zip file to compress it down from gigabytes down to megabytes to make it manageable.

[WorldOption.zip](https://github.com/cheahjs/palworld-save-tools/files/14429201/WorldOption.zip)

**Comment by Xavierix** [comment]
Hello, Having the same issue but with the Player File I am trying to convert. It is coming from a dedicated server. I have tried to convert the other characters on the account and the same issue. I am able to covert the Level,  and other level sav in that directory.  Just having the issue with any of the player sav files.

<--------
Decompressing sav file
Traceback (most recent call last):

  File "D:\Install Games\PalWorld\Pal_SaveGameData_test\palworld-save-tools-windows-v0.22.0\convert.py", line 160, in <module>
    main()
  File "D:\Install Games\PalWorld\Pal_SaveGameData_test\palworld-save-tools-windows-v0.22.0\convert.py", line 71, in main
    convert_sav_to_json(
  File "D:\Install Games\PalWorld\Pal_SaveGameData_test\palworld-save-tools-windows-v0.22.0\convert.py", line 105, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Install Games\PalWorld\Pal_SaveGameData_test\palworld-save-tools-windows-v0.22.0\palworld_save_tools\palsav.py", line 40, in decompress_sav_to_gvas
    raise Exception(f"incorrect compressed length: {compressed_len}")
Exception: incorrect compressed length: 13906
--------->
