### ISSUE TITLE
Incompatibility with v0.3.1.55394

### ISSUE THREAD

**Issue by Lancercmd** [cheahjs/palworld-save-tools#176]
**Have you modified the save files**
No.

**Have you tried the latest release**
Yes.

**Describe the bug**
```
Checking if Python is installed as python
C:\Users\Lan\AppData\Local\Programs\Python\Python312\python.exe
C:\Users\Lan\AppData\Local\Microsoft\WindowsApps\python.exe
Found Python at python
Python version:
Python 3.12.3
Converting C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\Level.sav to JSON, saving to C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\Level.sav.json
Decompressing sav file
Loading GVAS file
Traceback (most recent call last):
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\convert.py", line 160, in <module>
    main()
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\convert.py", line 71, in main
    convert_sav_to_json(
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\convert.py", line 114, in convert_sav_to_json
    gvas_file = GvasFile.read(
                ^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 510, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 537, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\archive.py", line 396, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\rawdata\map_object.py", line 21, in decode
    map_object["Model"]["value"]["RawData"]["value"] = map_model.decode_bytes(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lan\Desktop\palworld-save-tools-windows-v0.22.0\palworld_save_tools\rawdata\map_model.py", line 42, in decode_bytes
    raise Exception("Warning: EOF not reached")
Exception: Warning: EOF not reached
```

**Copy of .sav or .sav.json files**
[Level.zip](https://github.com/user-attachments/files/16009128/Level.zip)

**Comment by Lancercmd** [comment]
Solved with `v0.23.0`.
