### ISSUE TITLE
EOF not reached for EPalBaseCampModuleType::PassiveEffect

### ISSUE THREAD

**Issue by Cheers2Moon** [cheahjs/palworld-save-tools#179]
**Common issues before reporting**

**Have you modified the save files**
Nope, still trying to convert it to JSON in the first place. I used the custom argument in the pinned to remove world parsing data

**Have you tried the latest release**
Yes

**Describe the bug**
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect

There is also some other EOF stuff but that seems in line with issues already posted.

**Copy of .sav or .sav.json files**
[Level.zip](https://github.com/user-attachments/files/16033920/Level.zip)

``` Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Traceback (most recent call last):
  File "C:\Users\Username\Desktop\Palworld_Backup\Transfer Stuff\palworld-save-tools-windows-v0.22.0\palworld_save_tools\commands\convert.py", line 160, in <module>
    main()
  File "C:\Users\Username\Desktop\Palworld_Backup\Transfer Stuff\palworld-save-tools-windows-v0.22.0\palworld_save_tools\commands\convert.py", line 71, in main
    convert_sav_to_json(
  File "C:\Users\Username\Desktop\Palworld_Backup\Transfer Stuff\palworld-save-tools-windows-v0.22.0\palworld_save_tools\commands\convert.py", line 114, in convert_sav_to_json
    gvas_file = GvasFile.read(
                ^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 291, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 304, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 415, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 442, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 291, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 377, in property
    value = self.prop_value(value_type, value_struct_type, value_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 399, in prop_value
    return self.struct_value(struct_type_name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 442, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 291, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\archive.py", line 301, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\rawdata\item_container.py", line 13, in decode
    value["value"] = decode_bytes(reader, data_bytes)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\palworld_save_tools\rawdata\item_container.py", line 30, in decode_bytes
    raise Exception("Warning: EOF not reached")
Exception: Warning: EOF not reached```

**Comment by bullfrogberry** [comment]
I have the same problem I converted the world file from an xbox pal world save using https://github.com/Z1ni/XGP-save-extractor which then I was directed to use this script to convert it to JSON and get the same error as above
![cmd](https://github.com/cheahjs/palworld-save-tools/assets/13040266/acf41af8-6ddb-458b-bd22-5a8705e36eca)

**Comment by bakeair** [comment]
This issue occurred after the game was updated on June 27.
