### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by JadeCloudSerpentCultivatesTheEmperor** [cheahjs/palworld-save-tools#18]
Im trying to convert a player save file to json. It works initially but at a certain stage it says permission denied.

**Comment by thomas-steinthal** [comment]
same

**Comment by cheahjs** [comment]
Do you have a screenshot of what it says?

**Comment by echarles503** [comment]
Converting C:\Users\x\Downloads\palworld-save-tools-windows-v0.7.1\76561198056328245 to JSON (using C:\Users\x\Downloads\palworld-save-tools-windows-v0.7.1\uesave\uesave.exe)
Traceback (most recent call last):
  File "C:\Users\x\Downloads\palworld-save-tools-windows-v0.7.1\convert-single-sav-to-json.py", line 40, in <module>
    main()
  File "C:\Users\x\Downloads\palworld-save-tools-windows-v0.7.1\convert-single-sav-to-json.py", line 27, in main
    json_blob = convert_to_json(uesave_path, save_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\palworld-save-tools-windows-v0.7.1\lib\palsav.py", line 22, in convert_to_json
    with open(save_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\x\\Downloads\\palworld-save-tools-windows-v0.7.1\\76561198056328245'

**Comment by echarles503** [comment]
Fix: Drop the .sav file instead of the folder
