### ISSUE TITLE
 Unknown type: ByteProperty (.SaveParameter.Level)

### ISSUE THREAD

**Issue by Sun-can** [cheahjs/palworld-save-tools#197]
When I tried to drag the Level.sav file to convert.py on Windows, I got an error of Unknown type, but I did not have this problem when opening the sav file under Players.

### The following is the detailed error content：

D:\download\palworld\palworld-save-tools-windows-v0.23.1>python convert.py Level.sav
Converting Level.sav to JSON, saving to Level.sav.json
Decompressing sav file
Loading GVAS file
Traceback (most recent call last):
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\convert.py", line 164, in <module>
    main()
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\convert.py", line 75, in main
    convert_sav_to_json(
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\convert.py", line 118, in convert_sav_to_json
    gvas_file = GvasFile.read(
                ^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 515, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 477, in property
    value = self.prop_value(value_type, value_struct_type, value_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 499, in prop_value
    return self.struct_value(struct_type_name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 396, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\rawdata\character.py", line 13, in decode
    value["value"] = decode_bytes(reader, char_bytes)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
    "object": reader.properties_until_end(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 515, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\palworld\palworld-save-tools-windows-v0.23.1\palworld_save_tools\archive.py", line 493, in property
    raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: ByteProperty (.SaveParameter.Level)

**Comment by smugbatman** [comment]
I received the same error when trying to edit level.sav and came here to post this myself.

**Comment by Maickeenn** [comment]
I have the same problem, i believe the last update changed something in the format of the .sav file which is causing this error, do we have a work arround already ?

**Comment by youknowwhatsup** [comment]
I was using https://github.com/JannikBirn/palworld-host-save-fix to transfer character data from one to another. But that ran into an error. I saw that palworld-host-save-fix uses this repository as an library. (Where the parsing actually happens).

But yea i ran into the same error en followed it back to where it originated from.
I saw that the creater posted that he didn't had time to work on this project. https://github.com/cheahjs/palworld-save-tools/issues/194

I hope he can fix this soon.
