### ISSUE TITLE
Trying to convert my server save to local, the tools pops up" Unknown EPalWorkTransformType"

### ISSUE THREAD

**Issue by shadow211** [cheahjs/palworld-save-tools#198]
**Common issues before reporting**

**Have you modified the save files**
 No.

**Have you tried the latest release**
Yes.I used 0.24.0

**Describe the bug**

The pal server version is v0.4.12.64723.  I modifed the convert.cmd moved python ahead of python3 on line 15

Checking if Python is installed as python
C:\Program Files\Python310\python.exe
C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe
Found Python at python
Python version:
Python 3.10.7
Converting F:\SteamLibrary\steamapps\common\PalServer\Pal\Saved\SaveGames\0\205E6DCE47CC9E1473E2EBB6FD72ADEB（2）\Level.sav to JSON, saving to F:\SteamLibrary\steamapps\common\PalServer\Pal\Saved\SaveGames\0\205E6DCE47CC9E1473E2EBB6FD72ADEB（2）\Level.sav.json
Decompressing sav file
Loading GVAS file
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02aa63b90d65fd934e8579abecfc3c3028
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 0234705a6e5745fb478578b04f88c2df7a
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 022e46a97d1687f647b9c616e73f056839
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02d630bb95d58ff24aa44d6a73584f2897
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 0262ad11b39df8344786533fad4102f454
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02db4ccfe16de72b4ab022aea0db7d1983
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 0231bbd7867611c74fb842a1d9c52b102a
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 0238e2dd7ffe641f4eb6fe3e1c8d5a1680
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02db69c62964738445aef56eb6f5b5cfa2
Unknown EPalWorkTransformType, please report this: 63: EPalWorkableType::Progress: 02472f66a48d970245a6a7b0eafe805d24
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02b63c7831388fff40a6b49b9312930f5d
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 022161b4fa092eba4b96ca3ee9c044e67a
Unknown EPalWorkTransformType, please report this: 63: EPalWorkableType::Progress: 028702e1a0fa11304d892e1fffad5b5bdd
Unknown EPalWorkTransformType, please report this: 63: EPalWorkableType::Progress: 027aac705e8bf6744bafb286fe2f13a547
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 02ff47c88b40355b43a3e75ed4b7ab28c3
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 029b0c317c754320479376c446fc5acaf6
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 0212c0488c9badd842b678f3440596c2f6
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02bb4ad6d2607ca942aeccc47d108e336b
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 022542932b90d003438a0865613905f7b6
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 02e4246f6ef75c444aae22766eb39cf73c
Unknown EPalWorkTransformType, please report this: 63: EPalWorkableType::Progress: 0213137fb34180704aaff86b5bc278f98c
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 02c1b427bbf23798448291930cb372c9ec
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 02eb69e148a7c07c46a72bd1bfb768b405
Unknown EPalWorkTransformType, please report this: 65: EPalWorkableType::Progress: 02260eb382c783994b8cb2c4f9a0041767
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02284e85dd7c911b47967e0646c4ed6f3b
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 0258a3a99b082a0e4e83e53a32ec5350a3
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 021134a4d48e5fcb40b9859f67a427b724
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02e761ed446797cd4db566a864e23cbf95
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 022172f69ec30fd34692830a4a20cdfa31
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02836a2907846ae64ab429470694b2b004
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02c73d73192cd72540946174437f06f375
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02f6025bc39cd13142ab25ca6cc446c8f8
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 026c52468e8a604c4b8df1c8ef7a01fe03
Unknown EPalWorkTransformType, please report this: 63: EPalWorkableType::Progress: 02f29436b551cc9e419e73b9190aec813e
Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress: 02d42b10d4f14f7c4091790adc8d0221a9
Unknown EPalWorkTransformType, please report this: 0: EPalWorkableType::Progress: 02a26c209923d7d541881b460958d65f11
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 287, in fstring
    return data.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 2: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 290, in fstring
    escaped = data.decode(encoding, errors="surrogatepass")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 2: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\convert.py", line 164, in <module>
    main()
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\convert.py", line 75, in main
    convert_sav_to_json(
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\convert.py", line 118, in convert_sav_to_json
    gvas_file = GvasFile.read(
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 534, in struct
    value = self.struct_value(struct_type, path)
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 561, in struct_value
    return self.properties_until_end(path)
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 396, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\rawdata\group.py", line 17, in decode
    group["value"]["RawData"]["value"] = decode_bytes(
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\rawdata\group.py", line 71, in decode_bytes
    "player_name": reader.fstring(),
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 296, in fstring
    raise Exception(
Exception: Error decoding ascii string of length 23376: b'<`\xe4n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p\x96\xfb\xa2\n\x00\x00\x00\xfd\xff\xff\xff\x1ff\xd5u\x00\x001\x0b\x06^\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0\x89\x9d\x8af\x02\x00\x00\x06\x00\x00\x00ShiKi\x00\x9d\xff\xd2\xe6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\xb5\x8e\xe6C\x05\x00\x00\x05\x00\x00\x008848\x00\xb7V\xf4\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000\xec\xc4\xddf\x02\x00\x00\xfb\xff\xff\xff\xb0Q\xce\x91\x0f\\@\x88\x00'
**Copy of .sav or .sav.json files**
[Level.zip](https://github.com/user-attachments/files/18278773/Level.zip)

**Comment by Merlin8800** [comment]
I've been trying to tackle this issue to no avail, All i can say is it appears to be related to an issue with encrypting the save file back up when utilizing the new map_object container that were added in feybreak, such as Giant furnace, guild bank, Item retrieval machine, and such. I was able to convert my save back with progress transform errors after removing these items. There was a structure change to the game that has most assets now parenting off of a base into a common, possibly for the sony partnership with future DLC when it leaves early access.

**Comment by Merlin8800** [comment]
Update: I have found that there is a Raw Decryption byte and re-encryption byte issue with the archive of map_objects pertaining to ItemBooths and Palbooths Map ID Objects that needs to be addressed. 

Gvas will throw out errors if these objects are present in a world save at compression

**Comment by adx9802** [comment]
I was testing things out and removed all the new objects from the latest update and am still getting this issue. Is this the byte position you are mentioning?
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\palworld-save-tools-windows-v0.24.0\palworld_save_tools\archive.py", line 287, in fstring
    return data.decode(encoding)
           ~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 4: ordinal not in range(128)

**Comment by Merlin8800** [comment]
It's palbooths and itembooths. Either update the work.py with a EPalworkabletype::Booth at the header or remove palbooths and itembooths. Also make sure your group.py has been updated to kriscris' another pal save branch with the p(byte raw write and uint32 read/writer in the archive.py

**Comment by Aprexx** [comment]
I did what you said and the tool is running to the end and the .json is getting created. 
But I still get "Unknown EPalWorkTransformType, please report this: 64: EPalWorkableType::Progress" roughly 20+ times.

Do I just ignore these messages? I'm worried that converting back to .sav won't work.

**Comment by Merlin8800** [comment]
Byte for byte it will still convert. That's is from the localized progress and assignments from the podium. I.e. workee. The custom properties palworld needs to be updated, they went fun house mirrors with the parenting on the workflow in the blueprints and data array for those. It's outside my skill set at this time. But going on 150+ re-save of my test world, no issue or bloat. That data dumps irregular length raw and gets slapped back in the same, what doesn't work usually gets dropped, might explain on reload why pals all respawn at the palbox.

As a fun experiment, if you nuke all pal workability units in your base, i.e. furnace's, manufacturing belts etc. podium, those all vanish.

**Comment by Aprexx** [comment]
Exactly what I was worried about happened. I couldn't not convert my changes back:

![Image](https://github.com/user-attachments/assets/ce99dfe3-7377-4430-b57c-673801ee46e9)

I never mentioned what I tried to achieve:
My friend lost his character due to update or bad server and I'm trying to add him back using an older backup where I can still his Pals in Palworld Pal Editor
