### ISSUE TITLE
Exception: not a compressed Palworld save

### ISSUE THREAD

**Issue by hopgop1** [cheahjs/palworld-save-tools#52]
Hi,

Using the latest release, python 312, getting this error when trying to convert some of my saves. 

_"Converting C:\temp\oldsave\529B1B83000000000000000000000000.sav to JSON, saving to C:\temp\oldsave\529B1B83000000000000000000000000.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "C:\Users\user\Downloads\palworld-save-tools-windows-v0.11.0\convert.py", line 120, in <module>
    main()
  File "C:\Users\user\Downloads\palworld-save-tools-windows-v0.11.0\convert.py", line 52, in main
    convert_sav_to_json(args.filename, output_path, args.minify_json)
  File "C:\Users\user\Downloads\palworld-save-tools-windows-v0.11.0\convert.py", line 75, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\palworld-save-tools-windows-v0.11.0\lib\palsav.py", line 11, in decompress_sav_to_gvas
    raise Exception(
Exception: not a compressed Palworld save, found b'\x00\x00\x00' instead of P1Z_

[529B1B83000000000000000000000000.log](https://github.com/cheahjs/palworld-save-tools/files/14069115/529B1B83000000000000000000000000.log)

I've uploaded the save (renamed to .log so I can upload it), I suspect it's corrupted, but I'd appreciate if you could have a look. Thank you.

**Comment by cheahjs** [comment]
It is unfortunately a corrupted file, the entire file is entirely filled with zeroes.
