### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by Whatda18** [cheahjs/palworld-save-tools#54]
Checking if Python is installed as python3
C:\Users\Andrew\AppData\Local\Microsoft\WindowsApps\python3.exe
Found Python at python3
Python version:
Python 3.12.1
Converting C:\Users\Andrew\Desktop\Convert\Level.sav to JSON, saving to C:\Users\Andrew\Desktop\Convert\Level.sav.json
Decompressing sav file
Loading GVAS file
Traceback (most recent call last):
  File "C:\Users\Andrew\Desktop\Convert\convert.py", line 120, in <module>
    main()
  File "C:\Users\Andrew\Desktop\Convert\convert.py", line 52, in main
    convert_sav_to_json(args.filename, output_path, args.minify_json)
  File "C:\Users\Andrew\Desktop\Convert\convert.py", line 77, in convert_sav_to_json
    gvas_file = GvasFile.read(raw_gvas, PALWORLD_TYPE_HINTS, PALWORLD_CUSTOM_PROPERTIES)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\gvas.py", line 124, in read
    gvas_file.properties = reader.read_properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 166, in read_properties_until_end
    properties[name] = self.read_property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 175, in read_property
    value = self.read_struct(path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 287, in read_struct
    value = self.read_struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 323, in read_struct_value
    return self.read_properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 166, in read_properties_until_end
    properties[name] = self.read_property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 249, in read_property
    value = self.read_prop_value(value_type, value_struct_type, value_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 271, in read_prop_value
    return self.read_struct_value(struct_type_name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 323, in read_struct_value
    return self.read_properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 166, in read_properties_until_end
    properties[name] = self.read_property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Desktop\Convert\lib\archive.py", line 265, in read_property
    raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: n♥ArrayProper (.worldSaveData.ItemContainerSaveData.Value.Slots)
Press any key to continue . . .

any help would be appreciated.

**Comment by Whatda18** [comment]
[Uploading Level.zip…]()

**Comment by cheahjs** [comment]
The upload didn't complete before you commented, I am unable to debug this without the save file.

**Comment by Whatda18** [comment]
[Level.zip](https://github.com/cheahjs/palworld-save-tools/files/14069972/Level.zip)

**Comment by Whatda18** [comment]
Sorry, you were correct.  Here you go.  Thanks in advance.

**Comment by cheahjs** [comment]
No idea how your save got corrupted, there was a single instance of `ArrayProperty` that was corrupted into `n ArrayPropert`. Here's the save file with it fixed if you needed it.
[Level-54-05543010fix.sav.zip](https://github.com/cheahjs/palworld-save-tools/files/14076475/Level-54-05543010fix.sav.zip)

**Comment by triplesium** [comment]
> No idea how your save got corrupted, there was a single instance of `ArrayProperty` that was corrupted into `n ArrayPropert`. Here's the save file with it fixed if you needed it. [Level-54-05543010fix.sav.zip](https://github.com/cheahjs/palworld-save-tools/files/14076475/Level-54-05543010fix.sav.zip)

Hello. I have the same issue here and its type_name becomes 'n\x03ArrayProper'.
Could you tell me how you fixed it?

Here is the save file. Thank you very much.
[Level.zip](https://github.com/cheahjs/palworld-save-tools/files/14092523/Level.zip)
