### ISSUE TITLE
KeyError: 'package_file_version_ue4'

### ISSUE THREAD

**Issue by DBG-QT** [cheahjs/palworld-save-tools#57]
PS F:\download\palworld-save-tools-windows-v0.13.0> python .\convert.py C:\Users\Administrator\Desktop\Saved\Level.sav.json
Converting C:\Users\Administrator\Desktop\Saved\Level.sav.json to SAV, saving to C:\Users\Administrator\Desktop\Saved\Level.sav
Loading JSON from C:\Users\Administrator\Desktop\Saved\Level.sav.json
Traceback (most recent call last):
  File "F:\download\palworld-save-tools-windows-v0.13.0\convert.py", line 118, in <module>
    main()
  File "F:\download\palworld-save-tools-windows-v0.13.0\convert.py", line 63, in main
    convert_json_to_sav(args.filename, output_path)
  File "F:\download\palworld-save-tools-windows-v0.13.0\convert.py", line 93, in convert_json_to_sav
    gvas_file = GvasFile.load(data)
                ^^^^^^^^^^^^^^^^^^^
  File "F:\download\palworld-save-tools-windows-v0.13.0\lib\gvas.py", line 135, in load
    gvas_file.header = GvasHeader.load(dict["header"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\download\palworld-save-tools-windows-v0.13.0\lib\gvas.py", line 67, in load
    header.package_file_version_ue4 = dict["package_file_version_ue4"]
                                      ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'package_file_version_ue4'

**Comment by cheahjs** [comment]
If you are trying to convert a JSON file made by an older version, please use v0.7.1: https://github.com/cheahjs/palworld-save-tools/releases/download/v0.7.1/palworld-save-tools-windows-v0.7.1.zip
