### ISSUE TITLE
Unable to decompress Level.sav

### ISSUE THREAD

**Issue by taiQui** [cheahjs/palworld-save-tools#64]
Hey, 
As many player, my server just started after 1.13 and no more player or building was on server.
I tryied to investigate with the help of your tool but i'm unable to decompress Level.sav, if this file is corrupted, there is a way to fix it ?  I using lastest version of convert.py

this is the output:

```txt
C:\Users\user\Documents\temp\palworld-save-tools-windows-v0.13.0\pal>python3.11 convert.py Level.sav
Converting Level.sav to JSON, saving to Level.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "C:\Users\user\Documents\temp\palworld-save-tools-windows-v0.13.0\pal\convert.py", line 118, in <module>
    main()
  File "C:\Users\user\Documents\temp\palworld-save-tools-windows-v0.13.0\pal\convert.py", line 52, in main
    convert_sav_to_json(args.filename, output_path, args.minify_json)
  File "C:\Users\user\Documents\temp\palworld-save-tools-windows-v0.13.0\pal\convert.py", line 75, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\temp\palworld-save-tools-windows-v0.13.0\pal\lib\palsav.py", line 25, in decompress_sav_to_gvas
    uncompressed_data = zlib.decompress(data[12:])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: invalid block type
```

i joined the file
[Level.zip](https://github.com/cheahjs/palworld-save-tools/files/14074666/Level.zip)

**Comment by siakun** [comment]
I too am experiencing this problem... 😭

**Comment by cheahjs** [comment]
This is indicative of a corrupted save, nothing much I can do I'm afraid.

**Comment by taiQui** [comment]
Sad, thx you anyway
